### ISSUE TITLE
transMap tracks on new assemblies have wrong amino acid labels on negative strand

### ISSUE THREAD

**Issue by ifiddes** [ucsc-mus-strain-cactus/build_browser#13]
See http://hgwdev-mus-strain.cse.ucsc.edu/cgi-bin/hgTracks?hgS_doOtherUser=submit&hgS_otherUserName=ifiddes&hgS_otherUserSessionName=transmap_error

That is an inframe stop for ENSMUST00000128731.3, TGG -> TGA. The track shows a Tryptophan (W), which is the original TGG, but it is highlighted in red, so something knows that there is a problem there.

**Comment by joelarmstrong** [comment]
I think the track is meant to show the differences in J relative to NJ, much like the snakes, so this is probably intended. Maybe the other way around would make more sense for this use case though.

**Comment by diekhans** [comment]
this is control by the rendering mode.  It's show mRNA codons, which for transmap, these are the codons in the other species.  You can change this if you like in the track controls.
