### ISSUE TITLE
Need the ability to click through to mRNA/protein for bigGenePreds

### ISSUE THREAD

**Issue by ifiddes** [ucsc-mus-strain-cactus/build_browser#17]
See this example

http://hgwdev-mus-strain.cse.ucsc.edu/cgi-bin/hgc?hgsid=389370134_XBUsZTK6VHcLd3a5lP01o9uskz01&c=chr11&o=91839517&t=91880713&g=augustusCGP&i=g412.t1&l=91824088&r=91985165&db=MusCASTEiJ_1504

Error:

Can't start query:
select \* from augustusCGP where name = "g412.t1"
mySQL error 1146: Table 'MusCASTEiJ_1504.augustusCGP' doesn't exist (profile=, host=localhost, db=MusCASTEiJ_1504)

Do we need some sort of companion table for the bigGenePreds?

**Comment by joelarmstrong** [comment]
OK, fixed for augustus, but it still won't work for the transmap tracks.
