### ISSUE TITLE
Invalid signed integer 'no' for C57B6J

### ISSUE THREAD

**Issue by ifiddes** [ucsc-mus-strain-cactus/build_browser#7]

**Comment by diekhans** [comment]
Need help with this?

**Comment by ifiddes** [comment]
Yes please, if you have a chance. Just noticed it while working on writing
a script to set up all of the BAM alignments.

Ian Fiddes
PhD Student, Haussler lab
UC Santa Cruz Genomics Institute

**Comment by diekhans** [comment]
How do I reproduce?

**Comment by ifiddes** [comment]
I can't seem to reproduce this myself. Not sure what changed.
